events {}

http {

  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  # =========================
  # Upstreams
  # =========================
  upstream flowable_app {
    server flowable_app:8098;
  }

  upstream mayan_app {
      server mayan_app:8000;
  }

  # =========================
  # HTTP → HTTPS Redirect
  # =========================
  server {
    listen 80;
    return 301 https://$host$request_uri;
  }

  # =========================
  # HTTPS Server
  # =========================
  server {
    listen 443 ssl;

    ssl_certificate     /etc/nginx/ssl/nlsbanking_com.crt;
    ssl_certificate_key /etc/nginx/ssl/nlsbanking.key;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;

    # =========================
    # Flowable APIs
    # =========================
    location /flowable-service/ {
      proxy_pass http://flowable_app;

      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /mayan/ {
        proxy_pass http://mayan_app/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Forwarded-Prefix /mayan;
    }

    # =========================
    # React UI (keep LAST)
    # =========================
    location / {
      root      /usr/share/nginx/html;
      index     index.html;
      try_files $uri /index.html;
    }
  }
}